# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
