# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20160325_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
