# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belongings', '0003_remove_item_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id',
        ),
        migrations.AddField(
            model_name='sale',
            name='item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='belongings.Item'),
            preserve_default=False,
        ),
    ]
