# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belongings', '0004_auto_20160325_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_items', to='belongings.Receiver'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sale', serialize=False, to='belongings.Item'),
        ),
    ]
