# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belongings', '0005_auto_20160326_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
