# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belongings', '0006_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='receiver',
        ),
        migrations.AddField(
            model_name='sale',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
