# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belongings', '0007_auto_20160326_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStorage',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='storage', serialize=False, to='belongings.Item')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage', to='belongings.Box')),
                ('storage_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='belongings.StoragePlace')),
            ],
        ),
    ]
