# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belongings', '0008_itemstorage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='storage_place',
        ),
        migrations.RemoveField(
            model_name='item',
            name='box',
        ),
        migrations.RemoveField(
            model_name='item',
            name='storage_place',
        ),
    ]
