# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belongings', '0009_auto_20160326_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='storage_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='belongings.StoragePlace'),
        ),
    ]
